In [1]:
import numpy  as np 
import pandas as pn

In [8]:
data = np.arange(5,9)
panda_series = pn.Series(data=data)
index = ["A","B","C","D"]
panda_series = pn.Series(data=data,index=index)



panda_series

A    5
B    6
C    7
D    8
dtype: int64

In [11]:
panda_series.index = index
panda_series

A    5
B    6
C    7
D    8
dtype: int64

In [16]:
import pandas as pd

data = {"a": 2, "b": 3, "c": 4}

pd_series2 = pd.Series(data=data)
pd_series2

a    2
b    3
c    4
dtype: int64

pandas

In [18]:
data = np.random.rand(6,5)
data

array([[0.59629061, 0.11008173, 0.86716027, 0.95793941, 0.70720569],
       [0.32357425, 0.79803675, 0.81607766, 0.80133343, 0.28668878],
       [0.09281332, 0.84850621, 0.5368003 , 0.205169  , 0.26428996],
       [0.52645888, 0.05468754, 0.34433239, 0.37748079, 0.37098574],
       [0.53553253, 0.79584804, 0.35633751, 0.69897898, 0.41421695],
       [0.23927583, 0.13537561, 0.18394065, 0.89500609, 0.00528075]])

In [32]:
df = pd.DataFrame(
data=data,
index=["row0","row1","row2","row3","row4","row5"],
columns=["col0","col1","col2","col3","col4"])
type(df["col0"])

pandas.Series

In [36]:
df["clo5"]= np.random.rand(6)
df

          col0      col1      col2      col3      col4      clo5
row0  0.596291  0.110082  0.867160  0.957939  0.707206  0.811899
row1  0.323574  0.798037  0.816078  0.801333  0.286689  0.469788
row2  0.092813  0.848506  0.536800  0.205169  0.264290  0.371276
row3  0.526459  0.054688  0.344332  0.377481  0.370986  0.782345
row4  0.535533  0.795848  0.356338  0.698979  0.414217  0.096332
row5  0.239276  0.135376  0.183941  0.895006  0.005281  0.557222

pandas drop

In [49]:
drop =df.drop(columns="col4", inplace=True)
drop

KeyError: "['col4'] not found in axis"

In [50]:
df

          col0      col1      col2      col3
row0  0.596291  0.110082  0.867160  0.957939
row1  0.323574  0.798037  0.816078  0.801333
row2  0.092813  0.848506  0.536800  0.205169
row3  0.526459  0.054688  0.344332  0.377481
row4  0.535533  0.795848  0.356338  0.698979
row5  0.239276  0.135376  0.183941  0.895006

In [56]:
df.loc[["row3","row5"],["col0","col1","col2","col3"]]

          col0      col1      col2      col3
row3  0.526459  0.054688  0.344332  0.377481
row5  0.239276  0.135376  0.183941  0.895006

In [ ]:
df.iloc[1,]

np.float64(0.8013334274507893)

## pandas conditions

In [ ]:
data = np.random.randn(5,5)
df = pn.DataFrame(data=data,
index = ["a","b","c","d","e"]
)

datadf = df <0

df[datadf]

          0         1         2         3         4
a -0.528367       NaN       NaN       NaN -0.368464
b -0.043092       NaN       NaN       NaN -1.242884
c -0.122810 -1.957708 -0.618366 -2.395183       NaN
d -0.838034 -0.642924 -0.135848 -0.618818 -0.811657
e -0.605344 -0.623208 -1.980988 -0.130278 -0.975697